; DLL mimicking basic ntoskrnl functionalities for execution of drivers in user mode

CHARACTERISTICS equ IMAGE_FILE_EXECUTABLE_IMAGE | IMAGE_FILE_32BIT_MACHINE | IMAGE_FILE_DLL

%include '../onesec.hdr'

EntryPoint:
    retn 3 * 4

;%EXPORT DbgPrint
    mov ebx, [esp+4]        ; DbgPrint doesn't clear arguments from the stack
    push MB_ICONINFORMATION ; UINT uType
;%reloc 1
    push Driver             ; LPCTSTR lpCaption
    push ebx                ; LPCTSTR lpText
    push 0                  ; HWND hWnd
    call MessageBoxA
    retn                    ; doesn't pop out parameters
;%reloc 2
;%IMPORT user32.dll!MessageBoxA

;%EXPORT ExAllocatePool
    push PAGE_READWRITE     ; DWORD flProtect
    push MEM_COMMIT         ; DWORD flAllocationType
    push dword [esp + 8]    ; SIZE_T dwSize
    push 0                  ; LPVOID lpAddress
    call VirtualAlloc
    retn 2 * 4
;%reloc 2
;%IMPORT kernel32.dll!VirtualAlloc

;%EXPORT ExAllocatePoolWithTag
    push PAGE_READWRITE     ; DWORD flProtect
    push MEM_COMMIT         ; DWORD flAllocationType
    push dword [esp + 8]    ; SIZE_T dwSize
    push 0                  ; LPVOID lpAddress
    call VirtualAlloc
    retn 3 * 4

;%EXPORT RtlInitUnicodeString
;    push    edi
;    mov     edi, [esp+0Ch]
;    mov     edx, [esp+8]
;    mov     dword [edx], 0
;    mov     [edx+4], edi
;    or      edi, edi
;    jz      loc_403481
;
;    or      ecx, -1
;    xor     eax, eax
;    repne scasw
;    not     ecx
;    shl     ecx, 1
;    cmp     ecx, 0FFFEh
;    jbe     loc_403478
;
;    mov     ecx, 0FFFEh
;loc_403478:
;    mov     [edx+2], cx
;    dec     ecx
;    dec     ecx
;    mov     [edx], cx
;loc_403481:
;    pop     edi
    retn 2 * 4

;%EXPORT KeCancelTimer
    retn 1 * 4

;%EXPORT KeInitializeTimerEx
;%EXPORT MmPageEntireDriver
    retn 2 * 4

;%EXPORT KeDelayExecutionThread
;%EXPORT KeInitializeDpc
    retn 3 * 4

;%EXPORT KeSetTimerEx
    retn 4 * 4

;%EXPORT IoCreateDevice
    retn 7 * 4


; not handling their parameters correctly yet
;%EXPORT CcCanIWrite
;%EXPORT CcCopyRead
;%EXPORT CcCopyWrite
;%EXPORT CcDeferWrite
;%EXPORT CcFastCopyRead
;%EXPORT CcFastCopyWrite
;%EXPORT CcFastMdlReadWait
;%EXPORT CcFastReadNotPossible
;%EXPORT CcFastReadWait
;%EXPORT CcFlushCache
;%EXPORT CcGetDirtyPages
;%EXPORT CcGetFileObjectFromBcb
;%EXPORT CcGetFileObjectFromSectionPtrs
;%EXPORT CcGetFlushedValidData
;%EXPORT CcGetLsnForFileObject
;%EXPORT CcInitializeCacheMap
;%EXPORT CcIsThereDirtyData
;%EXPORT CcMapData
;%EXPORT CcMdlRead
;%EXPORT CcMdlReadComplete
;%EXPORT CcMdlWriteAbort
;%EXPORT CcMdlWriteComplete
;%EXPORT CcPinMappedData
;%EXPORT CcPinRead
;%EXPORT CcPrepareMdlWrite
;%EXPORT CcPreparePinWrite
;%EXPORT CcPurgeCacheSection
;%EXPORT CcRemapBcb
;%EXPORT CcRepinBcb
;%EXPORT CcScheduleReadAhead
;%EXPORT CcSetAdditionalCacheAttributes
;%EXPORT CcSetBcbOwnerPointer
;%EXPORT CcSetDirtyPageThreshold
;%EXPORT CcSetDirtyPinnedData
;%EXPORT CcSetFileSizes
;%EXPORT CcSetLogHandleForFile
;%EXPORT CcSetReadAheadGranularity
;%EXPORT CcUninitializeCacheMap
;%EXPORT CcUnpinData
;%EXPORT CcUnpinDataForThread
;%EXPORT CcUnpinRepinnedBcb
;%EXPORT CcWaitForCurrentLazyWriterActivity
;%EXPORT CcZeroData
;%EXPORT CmRegisterCallback
;%EXPORT CmUnRegisterCallback
;%EXPORT DbgBreakPoint
;%EXPORT DbgBreakPointWithStatus
;%EXPORT DbgLoadImageSymbols
;%EXPORT DbgPrintEx
;%EXPORT DbgPrintReturnControlC
;%EXPORT DbgPrompt
;%EXPORT DbgQueryDebugFilterState
;%EXPORT DbgSetDebugFilterState
;%EXPORT ExAcquireFastMutexUnsafe
;%EXPORT ExAcquireResourceExclusiveLite
;%EXPORT ExAcquireResourceSharedLite
;%EXPORT ExAcquireRundownProtection
;%EXPORT ExAcquireRundownProtectionEx
;%EXPORT ExAcquireSharedStarveExclusive
;%EXPORT ExAcquireSharedWaitForExclusive
;%EXPORT ExAllocateFromPagedLookasideList
;%EXPORT ExAllocatePoolWithQuota
;%EXPORT ExAllocatePoolWithQuotaTag
;%EXPORT ExAllocatePoolWithTagPriority
;%EXPORT ExConvertExclusiveToSharedLite
;%EXPORT ExCreateCallback
;%EXPORT ExDeleteNPagedLookasideList
;%EXPORT ExDeletePagedLookasideList
;%EXPORT ExDeleteResourceLite
;%EXPORT ExDesktopObjectType
;%EXPORT ExDisableResourceBoostLite
;%EXPORT ExEnumHandleTable
;%EXPORT ExEventObjectType
;%EXPORT ExExtendZone
;%EXPORT ExFreePool
;%EXPORT ExFreePoolWithTag
;%EXPORT ExFreeToPagedLookasideList
;%EXPORT ExGetCurrentProcessorCounts
;%EXPORT ExGetCurrentProcessorCpuUsage
;%EXPORT ExGetExclusiveWaiterCount
;%EXPORT ExGetPreviousMode
;%EXPORT ExGetSharedWaiterCount
;%EXPORT ExInitializeNPagedLookasideList
;%EXPORT ExInitializePagedLookasideList
;%EXPORT ExInitializeResourceLite
;%EXPORT ExInitializeRundownProtection
;%EXPORT ExInitializeZone
;%EXPORT ExInterlockedAddLargeInteger
;%EXPORT ExInterlockedAddLargeStatistic
;%EXPORT ExInterlockedAddUlong
;%EXPORT ExInterlockedCompareExchange64
;%EXPORT ExInterlockedDecrementLong
;%EXPORT ExInterlockedExchangeUlong
;%EXPORT ExInterlockedExtendZone
;%EXPORT ExInterlockedFlushSList
;%EXPORT ExInterlockedIncrementLong
;%EXPORT ExInterlockedInsertHeadList
;%EXPORT ExInterlockedInsertTailList
;%EXPORT ExInterlockedPopEntryList
;%EXPORT ExInterlockedPopEntrySList
;%EXPORT ExInterlockedPushEntryList
;%EXPORT ExInterlockedPushEntrySList
;%EXPORT ExInterlockedRemoveHeadList
;%EXPORT ExIsProcessorFeaturePresent
;%EXPORT ExIsResourceAcquiredExclusiveLite
;%EXPORT ExIsResourceAcquiredSharedLite
;%EXPORT ExLocalTimeToSystemTime
;%EXPORT ExNotifyCallback
;%EXPORT ExQueryPoolBlockSize
;%EXPORT ExQueueWorkItem
;%EXPORT ExRaiseAccessViolation
;%EXPORT ExRaiseDatatypeMisalignment
;%EXPORT ExRaiseException
;%EXPORT ExRaiseHardError
;%EXPORT ExRaiseStatus
;%EXPORT ExReInitializeRundownProtection
;%EXPORT ExRegisterCallback
;%EXPORT ExReinitializeResourceLite
;%EXPORT ExReleaseFastMutexUnsafe
;%EXPORT ExReleaseResourceForThreadLite
;%EXPORT ExReleaseResourceLite
;%EXPORT ExReleaseRundownProtection
;%EXPORT ExReleaseRundownProtectionEx
;%EXPORT ExRundownCompleted
;%EXPORT ExSemaphoreObjectType
;%EXPORT ExSetResourceOwnerPointer
;%EXPORT ExSetTimerResolution
;%EXPORT ExSystemExceptionFilter
;%EXPORT ExSystemTimeToLocalTime
;%EXPORT ExUnregisterCallback
;%EXPORT ExUuidCreate
;%EXPORT ExVerifySuite
;%EXPORT ExWaitForRundownProtectionRelease
;%EXPORT ExWindowStationObjectType
;%EXPORT ExfAcquirePushLockExclusive
;%EXPORT ExfAcquirePushLockShared
;%EXPORT ExfInterlockedAddUlong
;%EXPORT ExfInterlockedCompareExchange64
;%EXPORT ExfInterlockedInsertHeadList
;%EXPORT ExfInterlockedInsertTailList
;%EXPORT ExfInterlockedPopEntryList
;%EXPORT ExfInterlockedPushEntryList
;%EXPORT ExfInterlockedRemoveHeadList
;%EXPORT ExfReleasePushLock
;%EXPORT Exfi386InterlockedDecrementLong
;%EXPORT Exfi386InterlockedExchangeUlong
;%EXPORT Exfi386InterlockedIncrementLong
;%EXPORT Exi386InterlockedDecrementLong
;%EXPORT Exi386InterlockedExchangeUlong
;%EXPORT Exi386InterlockedIncrementLong
;%EXPORT FsRtlAcquireFileExclusive
;%EXPORT FsRtlAddLargeMcbEntry
;%EXPORT FsRtlAddMcbEntry
;%EXPORT FsRtlAddToTunnelCache
;%EXPORT FsRtlAllocateFileLock
;%EXPORT FsRtlAllocatePool
;%EXPORT FsRtlAllocatePoolWithQuota
;%EXPORT FsRtlAllocatePoolWithQuotaTag
;%EXPORT FsRtlAllocatePoolWithTag
;%EXPORT FsRtlAllocateResource
;%EXPORT FsRtlAreNamesEqual
;%EXPORT FsRtlBalanceReads
;%EXPORT FsRtlCheckLockForReadAccess
;%EXPORT FsRtlCheckLockForWriteAccess
;%EXPORT FsRtlCheckOplock
;%EXPORT FsRtlCopyRead
;%EXPORT FsRtlCopyWrite
;%EXPORT FsRtlCurrentBatchOplock
;%EXPORT FsRtlDeleteKeyFromTunnelCache
;%EXPORT FsRtlDeleteTunnelCache
;%EXPORT FsRtlDeregisterUncProvider
;%EXPORT FsRtlDissectDbcs
;%EXPORT FsRtlDissectName
;%EXPORT FsRtlDoesDbcsContainWildCards
;%EXPORT FsRtlDoesNameContainWildCards
;%EXPORT FsRtlFastCheckLockForRead
;%EXPORT FsRtlFastCheckLockForWrite
;%EXPORT FsRtlFastUnlockAll
;%EXPORT FsRtlFastUnlockAllByKey
;%EXPORT FsRtlFastUnlockSingle
;%EXPORT FsRtlFindInTunnelCache
;%EXPORT FsRtlFreeFileLock
;%EXPORT FsRtlGetFileSize
;%EXPORT FsRtlGetNextFileLock
;%EXPORT FsRtlGetNextLargeMcbEntry
;%EXPORT FsRtlGetNextMcbEntry
;%EXPORT FsRtlIncrementCcFastReadNoWait
;%EXPORT FsRtlIncrementCcFastReadNotPossible
;%EXPORT FsRtlIncrementCcFastReadResourceMiss
;%EXPORT FsRtlIncrementCcFastReadWait
;%EXPORT FsRtlInitializeFileLock
;%EXPORT FsRtlInitializeLargeMcb
;%EXPORT FsRtlInitializeMcb
;%EXPORT FsRtlInitializeOplock
;%EXPORT FsRtlInitializeTunnelCache
;%EXPORT FsRtlInsertPerFileObjectContext
;%EXPORT FsRtlInsertPerStreamContext
;%EXPORT FsRtlIsDbcsInExpression
;%EXPORT FsRtlIsFatDbcsLegal
;%EXPORT FsRtlIsHpfsDbcsLegal
;%EXPORT FsRtlIsNameInExpression
;%EXPORT FsRtlIsNtstatusExpected
;%EXPORT FsRtlIsPagingFile
;%EXPORT FsRtlIsTotalDeviceFailure
;%EXPORT FsRtlLegalAnsiCharacterArray
;%EXPORT FsRtlLookupLargeMcbEntry
;%EXPORT FsRtlLookupLastLargeMcbEntry
;%EXPORT FsRtlLookupLastLargeMcbEntryAndIndex
;%EXPORT FsRtlLookupLastMcbEntry
;%EXPORT FsRtlLookupMcbEntry
;%EXPORT FsRtlLookupPerFileObjectContext
;%EXPORT FsRtlLookupPerStreamContextInternal
;%EXPORT FsRtlMdlRead
;%EXPORT FsRtlMdlReadComplete
;%EXPORT FsRtlMdlReadCompleteDev
;%EXPORT FsRtlMdlReadDev
;%EXPORT FsRtlMdlWriteComplete
;%EXPORT FsRtlMdlWriteCompleteDev
;%EXPORT FsRtlNormalizeNtstatus
;%EXPORT FsRtlNotifyChangeDirectory
;%EXPORT FsRtlNotifyCleanup
;%EXPORT FsRtlNotifyFilterChangeDirectory
;%EXPORT FsRtlNotifyFilterReportChange
;%EXPORT FsRtlNotifyFullChangeDirectory
;%EXPORT FsRtlNotifyFullReportChange
;%EXPORT FsRtlNotifyInitializeSync
;%EXPORT FsRtlNotifyReportChange
;%EXPORT FsRtlNotifyUninitializeSync
;%EXPORT FsRtlNotifyVolumeEvent
;%EXPORT FsRtlNumberOfRunsInLargeMcb
;%EXPORT FsRtlNumberOfRunsInMcb
;%EXPORT FsRtlOplockFsctrl
;%EXPORT FsRtlOplockIsFastIoPossible
;%EXPORT FsRtlPostPagingFileStackOverflow
;%EXPORT FsRtlPostStackOverflow
;%EXPORT FsRtlPrepareMdlWrite
;%EXPORT FsRtlPrepareMdlWriteDev
;%EXPORT FsRtlPrivateLock
;%EXPORT FsRtlProcessFileLock
;%EXPORT FsRtlRegisterFileSystemFilterCallbacks
;%EXPORT FsRtlRegisterUncProvider
;%EXPORT FsRtlReleaseFile
;%EXPORT FsRtlRemoveLargeMcbEntry
;%EXPORT FsRtlRemoveMcbEntry
;%EXPORT FsRtlRemovePerFileObjectContext
;%EXPORT FsRtlRemovePerStreamContext
;%EXPORT FsRtlResetLargeMcb
;%EXPORT FsRtlSplitLargeMcb
;%EXPORT FsRtlSyncVolumes
;%EXPORT FsRtlTeardownPerStreamContexts
;%EXPORT FsRtlTruncateLargeMcb
;%EXPORT FsRtlTruncateMcb
;%EXPORT FsRtlUninitializeFileLock
;%EXPORT FsRtlUninitializeLargeMcb
;%EXPORT FsRtlUninitializeMcb
;%EXPORT FsRtlUninitializeOplock
;%EXPORT HalDispatchTable
;%EXPORT HalExamineMBR
;%EXPORT HalPrivateDispatchTable
;%EXPORT HeadlessDispatch
;%EXPORT InbvAcquireDisplayOwnership
;%EXPORT InbvCheckDisplayOwnership
;%EXPORT InbvDisplayString
;%EXPORT InbvEnableBootDriver
;%EXPORT InbvEnableDisplayString
;%EXPORT InbvInstallDisplayStringFilter
;%EXPORT InbvIsBootDriverInstalled
;%EXPORT InbvNotifyDisplayOwnershipLost
;%EXPORT InbvResetDisplay
;%EXPORT InbvSetScrollRegion
;%EXPORT InbvSetTextColor
;%EXPORT InbvSolidColorFill
;%EXPORT InitSafeBootMode
;%EXPORT InterlockedCompareExchange
;%EXPORT InterlockedDecrement
;%EXPORT InterlockedExchange
;%EXPORT InterlockedExchangeAdd
;%EXPORT InterlockedIncrement
;%EXPORT InterlockedPopEntrySList
;%EXPORT InterlockedPushEntrySList
;%EXPORT IoAcquireCancelSpinLock
;%EXPORT IoAcquireRemoveLockEx
;%EXPORT IoAcquireVpbSpinLock
;%EXPORT IoAdapterObjectType
;%EXPORT IoAllocateAdapterChannel
;%EXPORT IoAllocateController
;%EXPORT IoAllocateDriverObjectExtension
;%EXPORT IoAllocateErrorLogEntry
;%EXPORT IoAllocateIrp
;%EXPORT IoAllocateMdl
;%EXPORT IoAllocateWorkItem
;%EXPORT IoAssignDriveLetters
;%EXPORT IoAssignResources
;%EXPORT IoAttachDevice
;%EXPORT IoAttachDeviceByPointer
;%EXPORT IoAttachDeviceToDeviceStack
;%EXPORT IoAttachDeviceToDeviceStackSafe
;%EXPORT IoBuildAsynchronousFsdRequest
;%EXPORT IoBuildDeviceIoControlRequest
;%EXPORT IoBuildPartialMdl
;%EXPORT IoBuildSynchronousFsdRequest
;%EXPORT IoCallDriver
;%EXPORT IoCancelFileOpen
;%EXPORT IoCancelIrp
;%EXPORT IoCheckDesiredAccess
;%EXPORT IoCheckEaBufferValidity
;%EXPORT IoCheckFunctionAccess
;%EXPORT IoCheckQuerySetFileInformation
;%EXPORT IoCheckQuerySetVolumeInformation
;%EXPORT IoCheckQuotaBufferValidity
;%EXPORT IoCheckShareAccess
;%EXPORT IoCompleteRequest
;%EXPORT IoConnectInterrupt
;%EXPORT IoCreateController
;%EXPORT IoCreateDisk
;%EXPORT IoCreateDriver
;%EXPORT IoCreateFile
;%EXPORT IoCreateFileSpecifyDeviceObjectHint
;%EXPORT IoCreateNotificationEvent
;%EXPORT IoCreateStreamFileObject
;%EXPORT IoCreateStreamFileObjectEx
;%EXPORT IoCreateStreamFileObjectLite
;%EXPORT IoCreateSymbolicLink
;%EXPORT IoCreateSynchronizationEvent
;%EXPORT IoCreateUnprotectedSymbolicLink
;%EXPORT IoCsqInitialize
;%EXPORT IoCsqInsertIrp
;%EXPORT IoCsqRemoveIrp
;%EXPORT IoCsqRemoveNextIrp
;%EXPORT IoDeleteController
;%EXPORT IoDeleteDevice
;%EXPORT IoDeleteDriver
;%EXPORT IoDeleteSymbolicLink
;%EXPORT IoDetachDevice
;%EXPORT IoDeviceHandlerObjectSize
;%EXPORT IoDeviceHandlerObjectType
;%EXPORT IoDeviceObjectType
;%EXPORT IoDisconnectInterrupt
;%EXPORT IoDriverObjectType
;%EXPORT IoEnqueueIrp
;%EXPORT IoEnumerateDeviceObjectList
;%EXPORT IoFastQueryNetworkAttributes
;%EXPORT IoFileObjectType
;%EXPORT IoForwardAndCatchIrp
;%EXPORT IoForwardIrpSynchronously
;%EXPORT IoFreeController
;%EXPORT IoFreeErrorLogEntry
;%EXPORT IoFreeIrp
;%EXPORT IoFreeMdl
;%EXPORT IoFreeWorkItem
;%EXPORT IoGetAttachedDevice
;%EXPORT IoGetAttachedDeviceReference
;%EXPORT IoGetBaseFileSystemDeviceObject
;%EXPORT IoGetBootDiskInformation
;%EXPORT IoGetConfigurationInformation
;%EXPORT IoGetCurrentProcess
;%EXPORT IoGetDeviceAttachmentBaseRef
;%EXPORT IoGetDeviceInterfaceAlias
;%EXPORT IoGetDeviceInterfaces
;%EXPORT IoGetDeviceObjectPointer
;%EXPORT IoGetDeviceProperty
;%EXPORT IoGetDeviceToVerify
;%EXPORT IoGetDiskDeviceObject
;%EXPORT IoGetDmaAdapter
;%EXPORT IoGetDriverObjectExtension
;%EXPORT IoGetFileObjectGenericMapping
;%EXPORT IoGetInitialStack
;%EXPORT IoGetLowerDeviceObject
;%EXPORT IoGetRelatedDeviceObject
;%EXPORT IoGetRequestorProcess
;%EXPORT IoGetRequestorProcessId
;%EXPORT IoGetRequestorSessionId
;%EXPORT IoGetStackLimits
;%EXPORT IoGetTopLevelIrp
;%EXPORT IoInitializeIrp
;%EXPORT IoInitializeRemoveLockEx
;%EXPORT IoInitializeTimer
;%EXPORT IoInvalidateDeviceRelations
;%EXPORT IoInvalidateDeviceState
;%EXPORT IoIsFileOriginRemote
;%EXPORT IoIsOperationSynchronous
;%EXPORT IoIsSystemThread
;%EXPORT IoIsValidNameGraftingBuffer
;%EXPORT IoIsWdmVersionAvailable
;%EXPORT IoMakeAssociatedIrp
;%EXPORT IoOpenDeviceInterfaceRegistryKey
;%EXPORT IoOpenDeviceRegistryKey
;%EXPORT IoPageRead
;%EXPORT IoPnPDeliverServicePowerNotification
;%EXPORT IoQueryDeviceDescription
;%EXPORT IoQueryFileDosDeviceName
;%EXPORT IoQueryFileInformation
;%EXPORT IoQueryVolumeInformation
;%EXPORT IoQueueThreadIrp
;%EXPORT IoQueueWorkItem
;%EXPORT IoRaiseHardError
;%EXPORT IoRaiseInformationalHardError
;%EXPORT IoReadDiskSignature
;%EXPORT IoReadOperationCount
;%EXPORT IoReadPartitionTable
;%EXPORT IoReadPartitionTableEx
;%EXPORT IoReadTransferCount
;%EXPORT IoRegisterBootDriverReinitialization
;%EXPORT IoRegisterDeviceInterface
;%EXPORT IoRegisterDriverReinitialization
;%EXPORT IoRegisterFileSystem
;%EXPORT IoRegisterFsRegistrationChange
;%EXPORT IoRegisterLastChanceShutdownNotification
;%EXPORT IoRegisterPlugPlayNotification
;%EXPORT IoRegisterShutdownNotification
;%EXPORT IoReleaseCancelSpinLock
;%EXPORT IoReleaseRemoveLockAndWaitEx
;%EXPORT IoReleaseRemoveLockEx
;%EXPORT IoReleaseVpbSpinLock
;%EXPORT IoRemoveShareAccess
;%EXPORT IoReportDetectedDevice
;%EXPORT IoReportHalResourceUsage
;%EXPORT IoReportResourceForDetection
;%EXPORT IoReportResourceUsage
;%EXPORT IoReportTargetDeviceChange
;%EXPORT IoReportTargetDeviceChangeAsynchronous
;%EXPORT IoRequestDeviceEject
;%EXPORT IoReuseIrp
;%EXPORT IoSetCompletionRoutineEx
;%EXPORT IoSetDeviceInterfaceState
;%EXPORT IoSetDeviceToVerify
;%EXPORT IoSetFileOrigin
;%EXPORT IoSetHardErrorOrVerifyDevice
;%EXPORT IoSetInformation
;%EXPORT IoSetIoCompletion
;%EXPORT IoSetPartitionInformation
;%EXPORT IoSetPartitionInformationEx
;%EXPORT IoSetShareAccess
;%EXPORT IoSetStartIoAttributes
;%EXPORT IoSetSystemPartition
;%EXPORT IoSetThreadHardErrorMode
;%EXPORT IoSetTopLevelIrp
;%EXPORT IoStartNextPacket
;%EXPORT IoStartNextPacketByKey
;%EXPORT IoStartPacket
;%EXPORT IoStartTimer
;%EXPORT IoStatisticsLock
;%EXPORT IoStopTimer
;%EXPORT IoSynchronousInvalidateDeviceRelations
;%EXPORT IoSynchronousPageWrite
;%EXPORT IoThreadToProcess
;%EXPORT IoUnregisterFileSystem
;%EXPORT IoUnregisterFsRegistrationChange
;%EXPORT IoUnregisterPlugPlayNotification
;%EXPORT IoUnregisterShutdownNotification
;%EXPORT IoUpdateShareAccess
;%EXPORT IoValidateDeviceIoControlAccess
;%EXPORT IoVerifyPartitionTable
;%EXPORT IoVerifyVolume
;%EXPORT IoVolumeDeviceToDosName
;%EXPORT IoWMIAllocateInstanceIds
;%EXPORT IoWMIDeviceObjectToInstanceName
;%EXPORT IoWMIExecuteMethod
;%EXPORT IoWMIHandleToInstanceName
;%EXPORT IoWMIOpenBlock
;%EXPORT IoWMIQueryAllData
;%EXPORT IoWMIQueryAllDataMultiple
;%EXPORT IoWMIQuerySingleInstance
;%EXPORT IoWMIQuerySingleInstanceMultiple
;%EXPORT IoWMIRegistrationControl
;%EXPORT IoWMISetNotificationCallback
;%EXPORT IoWMISetSingleInstance
;%EXPORT IoWMISetSingleItem
;%EXPORT IoWMISuggestInstanceName
;%EXPORT IoWMIWriteEvent
;%EXPORT IoWriteErrorLogEntry
;%EXPORT IoWriteOperationCount
;%EXPORT IoWritePartitionTable
;%EXPORT IoWritePartitionTableEx
;%EXPORT IoWriteTransferCount
;%EXPORT IofCallDriver
;%EXPORT IofCompleteRequest
;%EXPORT KdDebuggerEnabled
;%EXPORT KdDebuggerNotPresent
;%EXPORT KdDisableDebugger
;%EXPORT KdEnableDebugger
;%EXPORT KdEnteredDebugger
;%EXPORT KdPollBreakIn
;%EXPORT KdPowerTransition
;%EXPORT Ke386CallBios
;%EXPORT Ke386IoSetAccessProcess
;%EXPORT Ke386QueryIoAccessMap
;%EXPORT Ke386SetIoAccessMap
;%EXPORT KeAcquireInStackQueuedSpinLockAtDpcLevel
;%EXPORT KeAcquireInterruptSpinLock
;%EXPORT KeAcquireSpinLockAtDpcLevel
;%EXPORT KeAddSystemServiceTable
;%EXPORT KeAreApcsDisabled
;%EXPORT KeAttachProcess
;%EXPORT KeBugCheck
;%EXPORT KeBugCheckEx
;%EXPORT KeCapturePersistentThreadState
;%EXPORT KeClearEvent
;%EXPORT KeConnectInterrupt
;%EXPORT KeDcacheFlushCount
;%EXPORT KeDeregisterBugCheckCallback
;%EXPORT KeDeregisterBugCheckReasonCallback
;%EXPORT KeDetachProcess
;%EXPORT KeDisconnectInterrupt
;%EXPORT KeEnterCriticalRegion
;%EXPORT KeEnterKernelDebugger
;%EXPORT KeFindConfigurationEntry
;%EXPORT KeFindConfigurationNextEntry
;%EXPORT KeFlushEntireTb
;%EXPORT KeFlushQueuedDpcs
;%EXPORT KeGetCurrentThread
;%EXPORT KeGetPreviousMode
;%EXPORT KeGetRecommendedSharedDataAlignment
;%EXPORT KeI386AbiosCall
;%EXPORT KeI386AllocateGdtSelectors
;%EXPORT KeI386Call16BitCStyleFunction
;%EXPORT KeI386Call16BitFunction
;%EXPORT KeI386FlatToGdtSelector
;%EXPORT KeI386GetLid
;%EXPORT KeI386MachineType
;%EXPORT KeI386ReleaseGdtSelectors
;%EXPORT KeI386ReleaseLid
;%EXPORT KeI386SetGdtSelector
;%EXPORT KeIcacheFlushCount
;%EXPORT KeInitializeApc
;%EXPORT KeInitializeDeviceQueue
;%EXPORT KeInitializeEvent
;%EXPORT KeInitializeInterrupt
;%EXPORT KeInitializeMutant
;%EXPORT KeInitializeMutex
;%EXPORT KeInitializeQueue
;%EXPORT KeInitializeSemaphore
;%EXPORT KeInitializeSpinLock
;%EXPORT KeInsertByKeyDeviceQueue
;%EXPORT KeInsertDeviceQueue
;%EXPORT KeInsertHeadQueue
;%EXPORT KeInsertQueue
;%EXPORT KeInsertQueueApc
;%EXPORT KeInsertQueueDpc
;%EXPORT KeIsAttachedProcess
;%EXPORT KeIsExecutingDpc
;%EXPORT KeLeaveCriticalRegion
;%EXPORT KeLoaderBlock
;%EXPORT KeNumberProcessors
;%EXPORT KeProfileInterrupt
;%EXPORT KeProfileInterruptWithSource
;%EXPORT KePulseEvent
;%EXPORT KeQueryActiveProcessors
;%EXPORT KeQueryInterruptTime
;%EXPORT KeQueryPriorityThread
;%EXPORT KeQueryRuntimeThread
;%EXPORT KeQuerySystemTime
;%EXPORT KeQueryTickCount
;%EXPORT KeQueryTimeIncrement
;%EXPORT KeRaiseUserException
;%EXPORT KeReadStateEvent
;%EXPORT KeReadStateMutant
;%EXPORT KeReadStateMutex
;%EXPORT KeReadStateQueue
;%EXPORT KeReadStateSemaphore
;%EXPORT KeReadStateTimer
;%EXPORT KeRegisterBugCheckCallback
;%EXPORT KeRegisterBugCheckReasonCallback
;%EXPORT KeReleaseInStackQueuedSpinLockFromDpcLevel
;%EXPORT KeReleaseInterruptSpinLock
;%EXPORT KeReleaseMutant
;%EXPORT KeReleaseMutex
;%EXPORT KeReleaseSemaphore
;%EXPORT KeReleaseSpinLockFromDpcLevel
;%EXPORT KeRemoveByKeyDeviceQueue
;%EXPORT KeRemoveByKeyDeviceQueueIfBusy
;%EXPORT KeRemoveDeviceQueue
;%EXPORT KeRemoveEntryDeviceQueue
;%EXPORT KeRemoveQueue
;%EXPORT KeRemoveQueueDpc
;%EXPORT KeRemoveSystemServiceTable
;%EXPORT KeResetEvent
;%EXPORT KeRestoreFloatingPointState
;%EXPORT KeRevertToUserAffinityThread
;%EXPORT KeRundownQueue
;%EXPORT KeSaveFloatingPointState
;%EXPORT KeSaveStateForHibernate
;%EXPORT KeServiceDescriptorTable
;%EXPORT KeSetAffinityThread
;%EXPORT KeSetBasePriorityThread
;%EXPORT KeSetDmaIoCoherency
;%EXPORT KeSetEvent
;%EXPORT KeSetEventBoostPriority
;%EXPORT KeSetIdealProcessorThread
;%EXPORT KeSetImportanceDpc
;%EXPORT KeSetKernelStackSwapEnable
;%EXPORT KeSetPriorityThread
;%EXPORT KeSetProfileIrql
;%EXPORT KeSetSystemAffinityThread
;%EXPORT KeSetTargetProcessorDpc
;%EXPORT KeSetTimeIncrement
;%EXPORT KeSetTimeUpdateNotifyRoutine
;%EXPORT KeSetTimer
;%EXPORT KeStackAttachProcess
;%EXPORT KeSynchronizeExecution
;%EXPORT KeTerminateThread
;%EXPORT KeTickCount
;%EXPORT KeUnstackDetachProcess
;%EXPORT KeUpdateRunTime
;%EXPORT KeUpdateSystemTime
;%EXPORT KeUserModeCallback
;%EXPORT KeWaitForMultipleObjects
;%EXPORT KeWaitForMutexObject
;%EXPORT KeWaitForSingleObject
;%EXPORT KefAcquireSpinLockAtDpcLevel
;%EXPORT KefReleaseSpinLockFromDpcLevel
;%EXPORT Kei386EoiHelper
;%EXPORT KiAcquireSpinLock
;%EXPORT KiBugCheckData
;%EXPORT KiCoprocessorError
;%EXPORT KiDeliverApc
;%EXPORT KiDispatchInterrupt
;%EXPORT KiEnableTimerWatchdog
;%EXPORT KiIpiServiceRoutine
;%EXPORT KiReleaseSpinLock
;%EXPORT KiUnexpectedInterrupt
;%EXPORT Kii386SpinOnSpinLock
;%EXPORT LdrAccessResource
;%EXPORT LdrEnumResources
;%EXPORT LdrFindResourceDirectory_U
;%EXPORT LdrFindResource_U
;%EXPORT LpcPortObjectType
;%EXPORT LpcRequestPort
;%EXPORT LpcRequestWaitReplyPort
;%EXPORT LsaCallAuthenticationPackage
;%EXPORT LsaDeregisterLogonProcess
;%EXPORT LsaFreeReturnBuffer
;%EXPORT LsaLogonUser
;%EXPORT LsaLookupAuthenticationPackage
;%EXPORT LsaRegisterLogonProcess
;%EXPORT Mm64BitPhysicalAddress
;%EXPORT MmAddPhysicalMemory
;%EXPORT MmAddVerifierThunks
;%EXPORT MmAdjustWorkingSetSize
;%EXPORT MmAdvanceMdl
;%EXPORT MmAllocateContiguousMemory
;%EXPORT MmAllocateContiguousMemorySpecifyCache
;%EXPORT MmAllocateMappingAddress
;%EXPORT MmAllocateNonCachedMemory
;%EXPORT MmAllocatePagesForMdl
;%EXPORT MmBuildMdlForNonPagedPool
;%EXPORT MmCanFileBeTruncated
;%EXPORT MmCommitSessionMappedView
;%EXPORT MmCreateMdl
;%EXPORT MmCreateSection
;%EXPORT MmDisableModifiedWriteOfSection
;%EXPORT MmFlushImageSection
;%EXPORT MmForceSectionClosed
;%EXPORT MmFreeContiguousMemory
;%EXPORT MmFreeContiguousMemorySpecifyCache
;%EXPORT MmFreeMappingAddress
;%EXPORT MmFreeNonCachedMemory
;%EXPORT MmFreePagesFromMdl
;%EXPORT MmGetPhysicalAddress
;%EXPORT MmGetPhysicalMemoryRanges
;%EXPORT MmGetSystemRoutineAddress
;%EXPORT MmGetVirtualForPhysical
;%EXPORT MmGrowKernelStack
;%EXPORT MmHighestUserAddress
;%EXPORT MmIsAddressValid
;%EXPORT MmIsDriverVerifying
;%EXPORT MmIsNonPagedSystemAddressValid
;%EXPORT MmIsRecursiveIoFault
;%EXPORT MmIsThisAnNtAsSystem
;%EXPORT MmIsVerifierEnabled
;%EXPORT MmLockPagableDataSection
;%EXPORT MmLockPagableImageSection
;%EXPORT MmLockPagableSectionByHandle
;%EXPORT MmMapIoSpace
;%EXPORT MmMapLockedPages
;%EXPORT MmMapLockedPagesSpecifyCache
;%EXPORT MmMapLockedPagesWithReservedMapping
;%EXPORT MmMapMemoryDumpMdl
;%EXPORT MmMapUserAddressesToPage
;%EXPORT MmMapVideoDisplay
;%EXPORT MmMapViewInSessionSpace
;%EXPORT MmMapViewInSystemSpace
;%EXPORT MmMapViewOfSection
;%EXPORT MmMarkPhysicalMemoryAsBad
;%EXPORT MmMarkPhysicalMemoryAsGood
;%EXPORT MmPrefetchPages
;%EXPORT MmProbeAndLockPages
;%EXPORT MmProbeAndLockProcessPages
;%EXPORT MmProbeAndLockSelectedPages
;%EXPORT MmProtectMdlSystemAddress
;%EXPORT MmQuerySystemSize
;%EXPORT MmRemovePhysicalMemory
;%EXPORT MmResetDriverPaging
;%EXPORT MmSectionObjectType
;%EXPORT MmSecureVirtualMemory
;%EXPORT MmSetAddressRangeModified
;%EXPORT MmSetBankedSection
;%EXPORT MmSizeOfMdl
;%EXPORT MmSystemRangeStart
;%EXPORT MmTrimAllSystemPagableMemory
;%EXPORT MmUnlockPagableImageSection
;%EXPORT MmUnlockPages
;%EXPORT MmUnmapIoSpace
;%EXPORT MmUnmapLockedPages
;%EXPORT MmUnmapReservedMapping
;%EXPORT MmUnmapVideoDisplay
;%EXPORT MmUnmapViewInSessionSpace
;%EXPORT MmUnmapViewInSystemSpace
;%EXPORT MmUnmapViewOfSection
;%EXPORT MmUnsecureVirtualMemory
;%EXPORT MmUserProbeAddress
;%EXPORT NlsAnsiCodePage
;%EXPORT NlsLeadByteInfo
;%EXPORT NlsMbCodePageTag
;%EXPORT NlsMbOemCodePageTag
;%EXPORT NlsOemCodePage
;%EXPORT NlsOemLeadByteInfo
;%EXPORT NtAddAtom
;%EXPORT NtAdjustPrivilegesToken
;%EXPORT NtAllocateLocallyUniqueId
;%EXPORT NtAllocateUuids
;%EXPORT NtAllocateVirtualMemory
;%EXPORT NtBuildNumber
;%EXPORT NtClose
;%EXPORT NtConnectPort
;%EXPORT NtCreateEvent
;%EXPORT NtCreateFile
;%EXPORT NtCreateSection
;%EXPORT NtDeleteAtom
;%EXPORT NtDeleteFile
;%EXPORT NtDeviceIoControlFile
;%EXPORT NtDuplicateObject
;%EXPORT NtDuplicateToken
;%EXPORT NtFindAtom
;%EXPORT NtFreeVirtualMemory
;%EXPORT NtFsControlFile
;%EXPORT NtGlobalFlag
;%EXPORT NtLockFile
;%EXPORT NtMakePermanentObject
;%EXPORT NtMapViewOfSection
;%EXPORT NtNotifyChangeDirectoryFile
;%EXPORT NtOpenFile
;%EXPORT NtOpenProcess
;%EXPORT NtOpenProcessToken
;%EXPORT NtOpenProcessTokenEx
;%EXPORT NtOpenThread
;%EXPORT NtOpenThreadToken
;%EXPORT NtOpenThreadTokenEx
;%EXPORT NtQueryDirectoryFile
;%EXPORT NtQueryEaFile
;%EXPORT NtQueryInformationAtom
;%EXPORT NtQueryInformationFile
;%EXPORT NtQueryInformationProcess
;%EXPORT NtQueryInformationThread
;%EXPORT NtQueryInformationToken
;%EXPORT NtQueryQuotaInformationFile
;%EXPORT NtQuerySecurityObject
;%EXPORT NtQuerySystemInformation
;%EXPORT NtQueryVolumeInformationFile
;%EXPORT NtReadFile
;%EXPORT NtRequestPort
;%EXPORT NtRequestWaitReplyPort
;%EXPORT NtSetEaFile
;%EXPORT NtSetEvent
;%EXPORT NtSetInformationFile
;%EXPORT NtSetInformationProcess
;%EXPORT NtSetInformationThread
;%EXPORT NtSetQuotaInformationFile
;%EXPORT NtSetSecurityObject
;%EXPORT NtSetVolumeInformationFile
;%EXPORT NtShutdownSystem
;%EXPORT NtTraceEvent
;%EXPORT NtUnlockFile
;%EXPORT NtVdmControl
;%EXPORT NtWaitForSingleObject
;%EXPORT NtWriteFile
;%EXPORT ObAssignSecurity
;%EXPORT ObCheckCreateObjectAccess
;%EXPORT ObCheckObjectAccess
;%EXPORT ObCloseHandle
;%EXPORT ObCreateObject
;%EXPORT ObCreateObjectType
;%EXPORT ObDereferenceObject
;%EXPORT ObDereferenceSecurityDescriptor
;%EXPORT ObFindHandleForObject
;%EXPORT ObGetObjectSecurity
;%EXPORT ObInsertObject
;%EXPORT ObLogSecurityDescriptor
;%EXPORT ObMakeTemporaryObject
;%EXPORT ObOpenObjectByName
;%EXPORT ObOpenObjectByPointer
;%EXPORT ObQueryNameString
;%EXPORT ObQueryObjectAuditingByHandle
;%EXPORT ObReferenceObjectByHandle
;%EXPORT ObReferenceObjectByName
;%EXPORT ObReferenceObjectByPointer
;%EXPORT ObReferenceSecurityDescriptor
;%EXPORT ObReleaseObjectSecurity
;%EXPORT ObSetHandleAttributes
;%EXPORT ObSetSecurityDescriptorInfo
;%EXPORT ObSetSecurityObjectByPointer
;%EXPORT ObfDereferenceObject
;%EXPORT ObfReferenceObject
;%EXPORT PfxFindPrefix
;%EXPORT PfxInitialize
;%EXPORT PfxInsertPrefix
;%EXPORT PfxRemovePrefix
;%EXPORT PoCallDriver
;%EXPORT PoCancelDeviceNotify
;%EXPORT PoQueueShutdownWorkItem
;%EXPORT PoRegisterDeviceForIdleDetection
;%EXPORT PoRegisterDeviceNotify
;%EXPORT PoRegisterSystemState
;%EXPORT PoRequestPowerIrp
;%EXPORT PoRequestShutdownEvent
;%EXPORT PoSetHiberRange
;%EXPORT PoSetPowerState
;%EXPORT PoSetSystemState
;%EXPORT PoShutdownBugCheck
;%EXPORT PoStartNextPowerIrp
;%EXPORT PoUnregisterSystemState
;%EXPORT ProbeForRead
;%EXPORT ProbeForWrite
;%EXPORT PsAssignImpersonationToken
;%EXPORT PsChargePoolQuota
;%EXPORT PsChargeProcessNonPagedPoolQuota
;%EXPORT PsChargeProcessPagedPoolQuota
;%EXPORT PsChargeProcessPoolQuota
;%EXPORT PsCreateSystemProcess
;%EXPORT PsCreateSystemThread
;%EXPORT PsDereferenceImpersonationToken
;%EXPORT PsDereferencePrimaryToken
;%EXPORT PsDisableImpersonation
;%EXPORT PsEstablishWin32Callouts
;%EXPORT PsGetContextThread
;%EXPORT PsGetCurrentProcess
;%EXPORT PsGetCurrentProcessId
;%EXPORT PsGetCurrentProcessSessionId
;%EXPORT PsGetCurrentThread
;%EXPORT PsGetCurrentThreadId
;%EXPORT PsGetCurrentThreadPreviousMode
;%EXPORT PsGetCurrentThreadStackBase
;%EXPORT PsGetCurrentThreadStackLimit
;%EXPORT PsGetJobLock
;%EXPORT PsGetJobSessionId
;%EXPORT PsGetJobUIRestrictionsClass
;%EXPORT PsGetProcessCreateTimeQuadPart
;%EXPORT PsGetProcessDebugPort
;%EXPORT PsGetProcessExitProcessCalled
;%EXPORT PsGetProcessExitStatus
;%EXPORT PsGetProcessExitTime
;%EXPORT PsGetProcessId
;%EXPORT PsGetProcessImageFileName
;%EXPORT PsGetProcessInheritedFromUniqueProcessId
;%EXPORT PsGetProcessJob
;%EXPORT PsGetProcessPeb
;%EXPORT PsGetProcessPriorityClass
;%EXPORT PsGetProcessSectionBaseAddress
;%EXPORT PsGetProcessSecurityPort
;%EXPORT PsGetProcessSessionId
;%EXPORT PsGetProcessWin32Process
;%EXPORT PsGetProcessWin32WindowStation
;%EXPORT PsGetThreadFreezeCount
;%EXPORT PsGetThreadHardErrorsAreDisabled
;%EXPORT PsGetThreadId
;%EXPORT PsGetThreadProcess
;%EXPORT PsGetThreadProcessId
;%EXPORT PsGetThreadSessionId
;%EXPORT PsGetThreadTeb
;%EXPORT PsGetThreadWin32Thread
;%EXPORT PsGetVersion
;%EXPORT PsImpersonateClient
;%EXPORT PsInitialSystemProcess
;%EXPORT PsIsProcessBeingDebugged
;%EXPORT PsIsSystemThread
;%EXPORT PsIsThreadImpersonating
;%EXPORT PsIsThreadTerminating
;%EXPORT PsJobType
;%EXPORT PsLookupProcessByProcessId
;%EXPORT PsLookupProcessThreadByCid
;%EXPORT PsLookupThreadByThreadId
;%EXPORT PsProcessType
;%EXPORT PsReferenceImpersonationToken
;%EXPORT PsReferencePrimaryToken
;%EXPORT PsRemoveCreateThreadNotifyRoutine
;%EXPORT PsRemoveLoadImageNotifyRoutine
;%EXPORT PsRestoreImpersonation
;%EXPORT PsReturnPoolQuota
;%EXPORT PsReturnProcessNonPagedPoolQuota
;%EXPORT PsReturnProcessPagedPoolQuota
;%EXPORT PsRevertThreadToSelf
;%EXPORT PsRevertToSelf
;%EXPORT PsSetContextThread
;%EXPORT PsSetCreateProcessNotifyRoutine
;%EXPORT PsSetCreateThreadNotifyRoutine
;%EXPORT PsSetJobUIRestrictionsClass
;%EXPORT PsSetLegoNotifyRoutine
;%EXPORT PsSetLoadImageNotifyRoutine
;%EXPORT PsSetProcessPriorityByClass
;%EXPORT PsSetProcessPriorityClass
;%EXPORT PsSetProcessSecurityPort
;%EXPORT PsSetProcessWin32Process
;%EXPORT PsSetProcessWindowStation
;%EXPORT PsSetThreadHardErrorsAreDisabled
;%EXPORT PsSetThreadWin32Thread
;%EXPORT PsTerminateSystemThread
;%EXPORT PsThreadType
;%EXPORT READ_REGISTER_BUFFER_UCHAR
;%EXPORT READ_REGISTER_BUFFER_ULONG
;%EXPORT READ_REGISTER_BUFFER_USHORT
;%EXPORT READ_REGISTER_UCHAR
;%EXPORT READ_REGISTER_ULONG
;%EXPORT READ_REGISTER_USHORT
;%EXPORT RtlAbsoluteToSelfRelativeSD
;%EXPORT RtlAddAccessAllowedAce
;%EXPORT RtlAddAccessAllowedAceEx
;%EXPORT RtlAddAce
;%EXPORT RtlAddAtomToAtomTable
;%EXPORT RtlAddRange
;%EXPORT RtlAllocateHeap
;%EXPORT RtlAnsiCharToUnicodeChar
;%EXPORT RtlAnsiStringToUnicodeSize
;%EXPORT RtlAnsiStringToUnicodeString
;%EXPORT RtlAppendAsciizToString
;%EXPORT RtlAppendStringToString
;%EXPORT RtlAppendUnicodeStringToString
;%EXPORT RtlAppendUnicodeToString
;%EXPORT RtlAreAllAccessesGranted
;%EXPORT RtlAreAnyAccessesGranted
;%EXPORT RtlAreBitsClear
;%EXPORT RtlAreBitsSet
;%EXPORT RtlAssert
;%EXPORT RtlCaptureContext
;%EXPORT RtlCaptureStackBackTrace
;%EXPORT RtlCharToInteger
;%EXPORT RtlCheckRegistryKey
;%EXPORT RtlClearAllBits
;%EXPORT RtlClearBit
;%EXPORT RtlClearBits
;%EXPORT RtlCompareMemory
;%EXPORT RtlCompareMemoryUlong
;%EXPORT RtlCompareString
;%EXPORT RtlCompareUnicodeString
;%EXPORT RtlCompressBuffer
;%EXPORT RtlCompressChunks
;%EXPORT RtlConvertLongToLargeInteger
;%EXPORT RtlConvertSidToUnicodeString
;%EXPORT RtlConvertUlongToLargeInteger
;%EXPORT RtlCopyLuid
;%EXPORT RtlCopyRangeList
;%EXPORT RtlCopySid
;%EXPORT RtlCopyString
;%EXPORT RtlCopyUnicodeString
;%EXPORT RtlCreateAcl
;%EXPORT RtlCreateAtomTable
;%EXPORT RtlCreateHeap
;%EXPORT RtlCreateRegistryKey
;%EXPORT RtlCreateSecurityDescriptor
;%EXPORT RtlCreateSystemVolumeInformationFolder
;%EXPORT RtlCreateUnicodeString
;%EXPORT RtlCustomCPToUnicodeN
;%EXPORT RtlDecompressBuffer
;%EXPORT RtlDecompressChunks
;%EXPORT RtlDecompressFragment
;%EXPORT RtlDelete
;%EXPORT RtlDeleteAce
;%EXPORT RtlDeleteAtomFromAtomTable
;%EXPORT RtlDeleteElementGenericTable
;%EXPORT RtlDeleteElementGenericTableAvl
;%EXPORT RtlDeleteNoSplay
;%EXPORT RtlDeleteOwnersRanges
;%EXPORT RtlDeleteRange
;%EXPORT RtlDeleteRegistryValue
;%EXPORT RtlDescribeChunk
;%EXPORT RtlDestroyAtomTable
;%EXPORT RtlDestroyHeap
;%EXPORT RtlDowncaseUnicodeString
;%EXPORT RtlEmptyAtomTable
;%EXPORT RtlEnlargedIntegerMultiply
;%EXPORT RtlEnlargedUnsignedDivide
;%EXPORT RtlEnlargedUnsignedMultiply
;%EXPORT RtlEnumerateGenericTable
;%EXPORT RtlEnumerateGenericTableAvl
;%EXPORT RtlEnumerateGenericTableLikeADirectory
;%EXPORT RtlEnumerateGenericTableWithoutSplaying
;%EXPORT RtlEnumerateGenericTableWithoutSplayingAvl
;%EXPORT RtlEqualLuid
;%EXPORT RtlEqualSid
;%EXPORT RtlEqualString
;%EXPORT RtlEqualUnicodeString
;%EXPORT RtlExtendedIntegerMultiply
;%EXPORT RtlExtendedLargeIntegerDivide
;%EXPORT RtlExtendedMagicDivide
;%EXPORT RtlFillMemory
;%EXPORT RtlFillMemoryUlong
;%EXPORT RtlFindClearBits
;%EXPORT RtlFindClearBitsAndSet
;%EXPORT RtlFindClearRuns
;%EXPORT RtlFindFirstRunClear
;%EXPORT RtlFindLastBackwardRunClear
;%EXPORT RtlFindLeastSignificantBit
;%EXPORT RtlFindLongestRunClear
;%EXPORT RtlFindMessage
;%EXPORT RtlFindMostSignificantBit
;%EXPORT RtlFindNextForwardRunClear
;%EXPORT RtlFindRange
;%EXPORT RtlFindSetBits
;%EXPORT RtlFindSetBitsAndClear
;%EXPORT RtlFindUnicodePrefix
;%EXPORT RtlFormatCurrentUserKeyPath
;%EXPORT RtlFreeAnsiString
;%EXPORT RtlFreeHeap
;%EXPORT RtlFreeOemString
;%EXPORT RtlFreeRangeList
;%EXPORT RtlFreeUnicodeString
;%EXPORT RtlGUIDFromString
;%EXPORT RtlGenerate8dot3Name
;%EXPORT RtlGetAce
;%EXPORT RtlGetCallersAddress
;%EXPORT RtlGetCompressionWorkSpaceSize
;%EXPORT RtlGetDaclSecurityDescriptor
;%EXPORT RtlGetDefaultCodePage
;%EXPORT RtlGetElementGenericTable
;%EXPORT RtlGetElementGenericTableAvl
;%EXPORT RtlGetFirstRange
;%EXPORT RtlGetGroupSecurityDescriptor
;%EXPORT RtlGetNextRange
;%EXPORT RtlGetNtGlobalFlags
;%EXPORT RtlGetOwnerSecurityDescriptor
;%EXPORT RtlGetSaclSecurityDescriptor
;%EXPORT RtlGetSetBootStatusData
;%EXPORT RtlGetVersion
;%EXPORT RtlHashUnicodeString
;%EXPORT RtlImageDirectoryEntryToData
;%EXPORT RtlImageNtHeader
;%EXPORT RtlInitAnsiString
;%EXPORT RtlInitCodePageTable
;%EXPORT RtlInitString
;%EXPORT RtlInitializeBitMap
;%EXPORT RtlInitializeGenericTable
;%EXPORT RtlInitializeGenericTableAvl
;%EXPORT RtlInitializeRangeList
;%EXPORT RtlInitializeSid
;%EXPORT RtlInitializeUnicodePrefix
;%EXPORT RtlInsertElementGenericTable
;%EXPORT RtlInsertElementGenericTableAvl
;%EXPORT RtlInsertElementGenericTableFull
;%EXPORT RtlInsertElementGenericTableFullAvl
;%EXPORT RtlInsertUnicodePrefix
;%EXPORT RtlInt64ToUnicodeString
;%EXPORT RtlIntegerToChar
;%EXPORT RtlIntegerToUnicode
;%EXPORT RtlIntegerToUnicodeString
;%EXPORT RtlInvertRangeList
;%EXPORT RtlIpv4AddressToStringA
;%EXPORT RtlIpv4AddressToStringExA
;%EXPORT RtlIpv4AddressToStringExW
;%EXPORT RtlIpv4AddressToStringW
;%EXPORT RtlIpv4StringToAddressA
;%EXPORT RtlIpv4StringToAddressExA
;%EXPORT RtlIpv4StringToAddressExW
;%EXPORT RtlIpv4StringToAddressW
;%EXPORT RtlIpv6AddressToStringA
;%EXPORT RtlIpv6AddressToStringExA
;%EXPORT RtlIpv6AddressToStringExW
;%EXPORT RtlIpv6AddressToStringW
;%EXPORT RtlIpv6StringToAddressA
;%EXPORT RtlIpv6StringToAddressExA
;%EXPORT RtlIpv6StringToAddressExW
;%EXPORT RtlIpv6StringToAddressW
;%EXPORT RtlIsGenericTableEmpty
;%EXPORT RtlIsGenericTableEmptyAvl
;%EXPORT RtlIsNameLegalDOS8Dot3
;%EXPORT RtlIsRangeAvailable
;%EXPORT RtlIsValidOemCharacter
;%EXPORT RtlLargeIntegerAdd
;%EXPORT RtlLargeIntegerArithmeticShift
;%EXPORT RtlLargeIntegerDivide
;%EXPORT RtlLargeIntegerNegate
;%EXPORT RtlLargeIntegerShiftLeft
;%EXPORT RtlLargeIntegerShiftRight
;%EXPORT RtlLargeIntegerSubtract
;%EXPORT RtlLengthRequiredSid
;%EXPORT RtlLengthSecurityDescriptor
;%EXPORT RtlLengthSid
;%EXPORT RtlLockBootStatusData
;%EXPORT RtlLookupAtomInAtomTable
;%EXPORT RtlLookupElementGenericTable
;%EXPORT RtlLookupElementGenericTableAvl
;%EXPORT RtlLookupElementGenericTableFull
;%EXPORT RtlLookupElementGenericTableFullAvl
;%EXPORT RtlMapGenericMask
;%EXPORT RtlMapSecurityErrorToNtStatus
;%EXPORT RtlMergeRangeLists
;%EXPORT RtlMoveMemory
;%EXPORT RtlMultiByteToUnicodeN
;%EXPORT RtlMultiByteToUnicodeSize
;%EXPORT RtlNextUnicodePrefix
;%EXPORT RtlNtStatusToDosError
;%EXPORT RtlNtStatusToDosErrorNoTeb
;%EXPORT RtlNumberGenericTableElements
;%EXPORT RtlNumberGenericTableElementsAvl
;%EXPORT RtlNumberOfClearBits
;%EXPORT RtlNumberOfSetBits
;%EXPORT RtlOemStringToCountedUnicodeString
;%EXPORT RtlOemStringToUnicodeSize
;%EXPORT RtlOemStringToUnicodeString
;%EXPORT RtlOemToUnicodeN
;%EXPORT RtlPinAtomInAtomTable
;%EXPORT RtlPrefetchMemoryNonTemporal
;%EXPORT RtlPrefixString
;%EXPORT RtlPrefixUnicodeString
;%EXPORT RtlQueryAtomInAtomTable
;%EXPORT RtlQueryRegistryValues
;%EXPORT RtlQueryTimeZoneInformation
;%EXPORT RtlRaiseException
;%EXPORT RtlRandom
;%EXPORT RtlRandomEx
;%EXPORT RtlRealPredecessor
;%EXPORT RtlRealSuccessor
;%EXPORT RtlRemoveUnicodePrefix
;%EXPORT RtlReserveChunk
;%EXPORT RtlSecondsSince1970ToTime
;%EXPORT RtlSecondsSince1980ToTime
;%EXPORT RtlSelfRelativeToAbsoluteSD
;%EXPORT RtlSelfRelativeToAbsoluteSD2
;%EXPORT RtlSetAllBits
;%EXPORT RtlSetBit
;%EXPORT RtlSetBits
;%EXPORT RtlSetDaclSecurityDescriptor
;%EXPORT RtlSetGroupSecurityDescriptor
;%EXPORT RtlSetOwnerSecurityDescriptor
;%EXPORT RtlSetSaclSecurityDescriptor
;%EXPORT RtlSetTimeZoneInformation
;%EXPORT RtlSizeHeap
;%EXPORT RtlSplay
;%EXPORT RtlStringFromGUID
;%EXPORT RtlSubAuthorityCountSid
;%EXPORT RtlSubAuthoritySid
;%EXPORT RtlSubtreePredecessor
;%EXPORT RtlSubtreeSuccessor
;%EXPORT RtlTestBit
;%EXPORT RtlTimeFieldsToTime
;%EXPORT RtlTimeToElapsedTimeFields
;%EXPORT RtlTimeToSecondsSince1970
;%EXPORT RtlTimeToSecondsSince1980
;%EXPORT RtlTimeToTimeFields
;%EXPORT RtlTraceDatabaseAdd
;%EXPORT RtlTraceDatabaseCreate
;%EXPORT RtlTraceDatabaseDestroy
;%EXPORT RtlTraceDatabaseEnumerate
;%EXPORT RtlTraceDatabaseFind
;%EXPORT RtlTraceDatabaseLock
;%EXPORT RtlTraceDatabaseUnlock
;%EXPORT RtlTraceDatabaseValidate
;%EXPORT RtlUlongByteSwap
;%EXPORT RtlUlonglongByteSwap
;%EXPORT RtlUnicodeStringToAnsiSize
;%EXPORT RtlUnicodeStringToAnsiString
;%EXPORT RtlUnicodeStringToCountedOemString
;%EXPORT RtlUnicodeStringToInteger
;%EXPORT RtlUnicodeStringToOemSize
;%EXPORT RtlUnicodeStringToOemString
;%EXPORT RtlUnicodeToCustomCPN
;%EXPORT RtlUnicodeToMultiByteN
;%EXPORT RtlUnicodeToMultiByteSize
;%EXPORT RtlUnicodeToOemN
;%EXPORT RtlUnlockBootStatusData
;%EXPORT RtlUnwind
;%EXPORT RtlUpcaseUnicodeChar
;%EXPORT RtlUpcaseUnicodeString
;%EXPORT RtlUpcaseUnicodeStringToAnsiString
;%EXPORT RtlUpcaseUnicodeStringToCountedOemString
;%EXPORT RtlUpcaseUnicodeStringToOemString
;%EXPORT RtlUpcaseUnicodeToCustomCPN
;%EXPORT RtlUpcaseUnicodeToMultiByteN
;%EXPORT RtlUpcaseUnicodeToOemN
;%EXPORT RtlUpperChar
;%EXPORT RtlUpperString
;%EXPORT RtlUshortByteSwap
;%EXPORT RtlValidRelativeSecurityDescriptor
;%EXPORT RtlValidSecurityDescriptor
;%EXPORT RtlValidSid
;%EXPORT RtlVerifyVersionInfo
;%EXPORT RtlVolumeDeviceToDosName
;%EXPORT RtlWalkFrameChain
;%EXPORT RtlWriteRegistryValue
;%EXPORT RtlZeroHeap
;%EXPORT RtlZeroMemory
;%EXPORT RtlxAnsiStringToUnicodeSize
;%EXPORT RtlxOemStringToUnicodeSize
;%EXPORT RtlxUnicodeStringToAnsiSize
;%EXPORT RtlxUnicodeStringToOemSize
;%EXPORT SeAccessCheck
;%EXPORT SeAppendPrivileges
;%EXPORT SeAssignSecurity
;%EXPORT SeAssignSecurityEx
;%EXPORT SeAuditHardLinkCreation
;%EXPORT SeAuditingFileEvents
;%EXPORT SeAuditingFileEventsWithContext
;%EXPORT SeAuditingFileOrGlobalEvents
;%EXPORT SeAuditingHardLinkEvents
;%EXPORT SeAuditingHardLinkEventsWithContext
;%EXPORT SeCaptureSecurityDescriptor
;%EXPORT SeCaptureSubjectContext
;%EXPORT SeCloseObjectAuditAlarm
;%EXPORT SeCreateAccessState
;%EXPORT SeCreateClientSecurity
;%EXPORT SeCreateClientSecurityFromSubjectContext
;%EXPORT SeDeassignSecurity
;%EXPORT SeDeleteAccessState
;%EXPORT SeDeleteObjectAuditAlarm
;%EXPORT SeExports
;%EXPORT SeFilterToken
;%EXPORT SeFreePrivileges
;%EXPORT SeImpersonateClient
;%EXPORT SeImpersonateClientEx
;%EXPORT SeLockSubjectContext
;%EXPORT SeMarkLogonSessionForTerminationNotification
;%EXPORT SeOpenObjectAuditAlarm
;%EXPORT SeOpenObjectForDeleteAuditAlarm
;%EXPORT SePrivilegeCheck
;%EXPORT SePrivilegeObjectAuditAlarm
;%EXPORT SePublicDefaultDacl
;%EXPORT SeQueryAuthenticationIdToken
;%EXPORT SeQueryInformationToken
;%EXPORT SeQuerySecurityDescriptorInfo
;%EXPORT SeQuerySessionIdToken
;%EXPORT SeRegisterLogonSessionTerminatedRoutine
;%EXPORT SeReleaseSecurityDescriptor
;%EXPORT SeReleaseSubjectContext
;%EXPORT SeSetAccessStateGenericMapping
;%EXPORT SeSetSecurityDescriptorInfo
;%EXPORT SeSetSecurityDescriptorInfoEx
;%EXPORT SeSinglePrivilegeCheck
;%EXPORT SeSystemDefaultDacl
;%EXPORT SeTokenImpersonationLevel
;%EXPORT SeTokenIsAdmin
;%EXPORT SeTokenIsRestricted
;%EXPORT SeTokenIsWriteRestricted
;%EXPORT SeTokenObjectType
;%EXPORT SeTokenType
;%EXPORT SeUnlockSubjectContext
;%EXPORT SeUnregisterLogonSessionTerminatedRoutine
;%EXPORT SeValidSecurityDescriptor
;%EXPORT VerSetConditionMask
;%EXPORT VfFailDeviceNode
;%EXPORT VfFailDriver
;%EXPORT VfFailSystemBIOS
;%EXPORT VfIsVerificationEnabled
;%EXPORT WRITE_REGISTER_BUFFER_UCHAR
;%EXPORT WRITE_REGISTER_BUFFER_ULONG
;%EXPORT WRITE_REGISTER_BUFFER_USHORT
;%EXPORT WRITE_REGISTER_UCHAR
;%EXPORT WRITE_REGISTER_ULONG
;%EXPORT WRITE_REGISTER_USHORT
;%EXPORT WmiFlushTrace
;%EXPORT WmiGetClock
;%EXPORT WmiQueryTrace
;%EXPORT WmiQueryTraceInformation
;%EXPORT WmiStartTrace
;%EXPORT WmiStopTrace
;%EXPORT WmiTraceMessage
;%EXPORT WmiTraceMessageVa
;%EXPORT WmiUpdateTrace
;%EXPORT XIPDispatch
;%EXPORT ZwAccessCheckAndAuditAlarm
;%EXPORT ZwAddBootEntry
;%EXPORT ZwAdjustPrivilegesToken
;%EXPORT ZwAlertThread
;%EXPORT ZwAllocateVirtualMemory
;%EXPORT ZwAssignProcessToJobObject
;%EXPORT ZwCancelIoFile
;%EXPORT ZwCancelTimer
;%EXPORT ZwClearEvent
;%EXPORT ZwClose
;%EXPORT ZwCloseObjectAuditAlarm
;%EXPORT ZwConnectPort
;%EXPORT ZwCreateDirectoryObject
;%EXPORT ZwCreateEvent
;%EXPORT ZwCreateFile
;%EXPORT ZwCreateJobObject
;%EXPORT ZwCreateKey
;%EXPORT ZwCreateSection
;%EXPORT ZwCreateSymbolicLinkObject
;%EXPORT ZwCreateTimer
;%EXPORT ZwDeleteBootEntry
;%EXPORT ZwDeleteFile
;%EXPORT ZwDeleteKey
;%EXPORT ZwDeleteValueKey
;%EXPORT ZwDeviceIoControlFile
;%EXPORT ZwDisplayString
;%EXPORT ZwDuplicateObject
;%EXPORT ZwDuplicateToken
;%EXPORT ZwEnumerateBootEntries
;%EXPORT ZwEnumerateKey
;%EXPORT ZwEnumerateValueKey
;%EXPORT ZwFlushInstructionCache
;%EXPORT ZwFlushKey
;%EXPORT ZwFlushVirtualMemory
;%EXPORT ZwFreeVirtualMemory
;%EXPORT ZwFsControlFile
;%EXPORT ZwInitiatePowerAction
;%EXPORT ZwIsProcessInJob
;%EXPORT ZwLoadDriver
;%EXPORT ZwLoadKey
;%EXPORT ZwMakeTemporaryObject
;%EXPORT ZwMapViewOfSection
;%EXPORT ZwNotifyChangeKey
;%EXPORT ZwOpenDirectoryObject
;%EXPORT ZwOpenEvent
;%EXPORT ZwOpenFile
;%EXPORT ZwOpenJobObject
;%EXPORT ZwOpenKey
;%EXPORT ZwOpenProcess
;%EXPORT ZwOpenProcessToken
;%EXPORT ZwOpenProcessTokenEx
;%EXPORT ZwOpenSection
;%EXPORT ZwOpenSymbolicLinkObject
;%EXPORT ZwOpenThread
;%EXPORT ZwOpenThreadToken
;%EXPORT ZwOpenThreadTokenEx
;%EXPORT ZwOpenTimer
;%EXPORT ZwPowerInformation
;%EXPORT ZwPulseEvent
;%EXPORT ZwQueryBootEntryOrder
;%EXPORT ZwQueryBootOptions
;%EXPORT ZwQueryDefaultLocale
;%EXPORT ZwQueryDefaultUILanguage
;%EXPORT ZwQueryDirectoryFile
;%EXPORT ZwQueryDirectoryObject
;%EXPORT ZwQueryEaFile
;%EXPORT ZwQueryFullAttributesFile
;%EXPORT ZwQueryInformationFile
;%EXPORT ZwQueryInformationJobObject
;%EXPORT ZwQueryInformationProcess
;%EXPORT ZwQueryInformationThread
;%EXPORT ZwQueryInformationToken
;%EXPORT ZwQueryInstallUILanguage
;%EXPORT ZwQueryKey
;%EXPORT ZwQueryObject
;%EXPORT ZwQuerySection
;%EXPORT ZwQuerySecurityObject
;%EXPORT ZwQuerySymbolicLinkObject
;%EXPORT ZwQuerySystemInformation
;%EXPORT ZwQueryValueKey
;%EXPORT ZwQueryVolumeInformationFile
;%EXPORT ZwReadFile
;%EXPORT ZwReplaceKey
;%EXPORT ZwRequestWaitReplyPort
;%EXPORT ZwResetEvent
;%EXPORT ZwRestoreKey
;%EXPORT ZwSaveKey
;%EXPORT ZwSaveKeyEx
;%EXPORT ZwSetBootEntryOrder
;%EXPORT ZwSetBootOptions
;%EXPORT ZwSetDefaultLocale
;%EXPORT ZwSetDefaultUILanguage
;%EXPORT ZwSetEaFile
;%EXPORT ZwSetEvent
;%EXPORT ZwSetInformationFile
;%EXPORT ZwSetInformationJobObject
;%EXPORT ZwSetInformationObject
;%EXPORT ZwSetInformationProcess
;%EXPORT ZwSetInformationThread
;%EXPORT ZwSetSecurityObject
;%EXPORT ZwSetSystemInformation
;%EXPORT ZwSetSystemTime
;%EXPORT ZwSetTimer
;%EXPORT ZwSetValueKey
;%EXPORT ZwSetVolumeInformationFile
;%EXPORT ZwTerminateJobObject
;%EXPORT ZwTerminateProcess
;%EXPORT ZwTranslateFilePath
;%EXPORT ZwUnloadDriver
;%EXPORT ZwUnloadKey
;%EXPORT ZwUnmapViewOfSection
;%EXPORT ZwWaitForMultipleObjects
;%EXPORT ZwWaitForSingleObject
;%EXPORT ZwWriteFile
;%EXPORT ZwYieldExecution
;%EXPORT _CIcos
;%EXPORT _CIsin
;%EXPORT _CIsqrt
;%EXPORT _abnormal_termination
;%EXPORT _alldiv
;%EXPORT _alldvrm
;%EXPORT _allmul
;%EXPORT _alloca_probe
;%EXPORT _allrem
;%EXPORT _allshl
;%EXPORT _allshr
;%EXPORT _aulldiv
;%EXPORT _aulldvrm
;%EXPORT _aullrem
;%EXPORT _aullshr
;%EXPORT _except_handler2
;%EXPORT _except_handler3
;%EXPORT _global_unwind2
;%EXPORT _itoa
;%EXPORT _itow
;%EXPORT _local_unwind2
;%EXPORT _purecall
;%EXPORT _snprintf
;%EXPORT _snwprintf
;%EXPORT _stricmp
;%EXPORT _strlwr
;%EXPORT _strnicmp
;%EXPORT _strnset
;%EXPORT _strrev
;%EXPORT _strset
;%EXPORT _strupr
;%EXPORT _vsnprintf
;%EXPORT _vsnwprintf
;%EXPORT _wcsicmp
;%EXPORT _wcslwr
;%EXPORT _wcsnicmp
;%EXPORT _wcsnset
;%EXPORT _wcsrev
;%EXPORT _wcsupr
;%EXPORT atoi
;%EXPORT atol
;%EXPORT isdigit
;%EXPORT islower
;%EXPORT isprint
;%EXPORT isspace
;%EXPORT isupper
;%EXPORT isxdigit
;%EXPORT mbstowcs
;%EXPORT mbtowc
;%EXPORT memchr
;%EXPORT memcpy
;%EXPORT memmove
;%EXPORT memset
;%EXPORT qsort
;%EXPORT rand
;%EXPORT sprintf
;%EXPORT srand
;%EXPORT strcat
;%EXPORT strchr
;%EXPORT strcmp
;%EXPORT strcpy
;%EXPORT strlen
;%EXPORT strncat
;%EXPORT strncmp
;%EXPORT strncpy
;%EXPORT strrchr
;%EXPORT strspn
;%EXPORT strstr
;%EXPORT swprintf
;%EXPORT tolower
;%EXPORT toupper
;%EXPORT towlower
;%EXPORT towupper
;%EXPORT vDbgPrintEx
;%EXPORT vDbgPrintExWithPrefix
;%EXPORT vsprintf
;%EXPORT wcscat
;%EXPORT wcschr
;%EXPORT wcscmp
;%EXPORT wcscpy
;%EXPORT wcscspn
;%EXPORT wcslen
;%EXPORT wcsncat
;%EXPORT wcsncmp
;%EXPORT wcsncpy
;%EXPORT wcsrchr
;%EXPORT wcsspn
;%EXPORT wcsstr
;%EXPORT wcstombs
;%EXPORT wctomb
    ret

Driver db "User mode Ntoskrnl", 0

;%IMPORTS

;%EXPORTS ntoskrnl.exe

;%relocs

SECTION0SIZE equ $ - Section0Start
SIZEOFIMAGE equ $ - IMAGEBASE

;Ange Albertini, Creative Commons BY, 2010
